# Generated by Django 2.0.6 on 2019-06-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章名')),
                ('img', models.ImageField(upload_to='article', verbose_name='插图')),
                ('details', models.TextField(verbose_name='正文')),
                ('is_show', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Article_Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='文章分类')),
                ('img', models.ImageField(default='articleCate/1.png', upload_to='articleCate', verbose_name='插图')),
            ],
            options={
                'db_table': 'article_cate',
            },
        ),
        migrations.CreateModel(
            name='Auxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='辅料名', max_length=10)),
                ('number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dish_auxi',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'community',
            },
        ),
        migrations.CreateModel(
            name='CreateDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'createdish',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='难度')),
            ],
            options={
                'db_table': 'dish_degree',
            },
        ),
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text11', models.TextField()),
                ('addTime', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'demo',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='名字')),
                ('img', models.ImageField(upload_to='dish', verbose_name='图片')),
                ('descs', models.TextField(null=True, verbose_name='描述')),
                ('details', models.TextField(null=True, verbose_name='小窍门')),
                ('addTime', models.DateField(default='2019-02-26')),
                ('number', models.IntegerField(default=0, null=True, verbose_name='收藏数')),
                ('is_show', models.BooleanField(default=False)),
                ('degree', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Degree')),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Dish_Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名')),
            ],
            options={
                'db_table': 'dish_cate',
            },
        ),
        migrations.CreateModel(
            name='Dish_Cate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名')),
            ],
            options={
                'db_table': 'Dish_Cate2',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(max_length=255, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Ingre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='食材名')),
                ('img', models.ImageField(upload_to='ingre', verbose_name='图片')),
                ('descs', models.TextField(null=True, verbose_name='选购技巧')),
                ('details', models.TextField(null=True, verbose_name='营养功效')),
                ('price', models.IntegerField(default=30, null=True, verbose_name='价格')),
                ('is_show', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ingre',
            },
        ),
        migrations.CreateModel(
            name='Ingre_Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名')),
            ],
            options={
                'db_table': 'Ingre_Cate',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='主料名', max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish')),
            ],
            options={
                'db_table': 'dish_main',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish')),
                ('dish_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Dish_Cate')),
            ],
            options={
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Ingre')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='工艺名')),
            ],
            options={
                'db_table': 'dish_skill',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textStep1', models.CharField(default=1, max_length=5, verbose_name='步骤序号')),
                ('textStep2', models.TextField(verbose_name='步骤内容')),
                ('imgStep', models.ImageField(upload_to='dishStep', verbose_name='步骤图片')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish')),
            ],
            options={
                'db_table': 'dish_Step',
            },
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='口味名')),
            ],
            options={
                'db_table': 'dish_taste',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='所需时间')),
            ],
            options={
                'db_table': 'dish_time',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='姓名')),
                ('img', models.ImageField(default='img/user.png', upload_to='img', verbose_name='头像')),
                ('email', models.EmailField(max_length=25, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
                ('address', models.CharField(default='暂无地址', max_length=50, verbose_name='地址')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.IntegerField(default=0, verbose_name='是否激活')),
                ('user_Community', models.ManyToManyField(related_name='userCommunity', through='myApp.Community', to='myApp.Dish')),
                ('user_cart', models.ManyToManyField(related_name='userCart', through='myApp.Cart', to='myApp.Ingre')),
                ('user_collection', models.ManyToManyField(related_name='userCollection', through='myApp.Collection', to='myApp.Dish')),
                ('user_comment', models.ManyToManyField(related_name='userComment', through='myApp.Comment', to='myApp.Dish')),
                ('user_feedback', models.ManyToManyField(related_name='userFeedback', through='myApp.Feedback', to='myApp.Ingre')),
                ('user_oder', models.ManyToManyField(related_name='userOrder', through='myApp.Order', to='myApp.Ingre')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='ingre',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Ingre_Cate'),
        ),
        migrations.AddField(
            model_name='ingre',
            name='create',
            field=models.ManyToManyField(related_name='createDish', through='myApp.CreateDish', to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Ingre'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='dish_cate',
            name='cate_dish',
            field=models.ManyToManyField(related_name='cateDish', through='myApp.Menu', to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='dish_cate',
            name='dish_cate2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Dish_Cate2'),
        ),
        migrations.AddField(
            model_name='dish',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Skill'),
        ),
        migrations.AddField(
            model_name='dish',
            name='taste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Taste'),
        ),
        migrations.AddField(
            model_name='dish',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Time'),
        ),
        migrations.AddField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='createdish',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='createdish',
            name='ingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Ingre'),
        ),
        migrations.AddField(
            model_name='community',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='community',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ingre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Ingre'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.User'),
        ),
        migrations.AddField(
            model_name='auxi',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Dish'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Article_Cate'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('dish_cate', 'dish')},
        ),
        migrations.AlterUniqueTogether(
            name='dish',
            unique_together={('name', 'img')},
        ),
    ]
