# Generated by Django 2.0.6 on 2019-06-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20190627_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.Article_Cate'),
        ),
    ]
